site_name: TIPS
site_description: This is my yummy tips
site_author: aYukiYoshida
site_url: https://ayukiyoshida.github.io/tips
repo_url: https://github.com/aYukiYoshida/tips

nav:
    - TOP: index.md
    - STATISTICS: 
        - descriptive statistics: statistics/descriptive_statistics.md
        - outlie: statistics/outlie.md
        - significance: statistics/significance.md
        - statistical hypothesis: statistics/statistical_hypothesis.md   
        - statistics/ftest.md
        - statistics/run_test.md
        - Bayesian:
            - Bayesian estimation: statistics/bayesian/bayesian_estimation.md
            - Bayesian statistics: statistics/bayesian/bayesian_statistics.md
    - NLP:
        - How to install tools: nlp/install_tools.md
    - Python:
        - Setup : python/setup.md
    - LaTeX:
        - Horizontal line in LaTeX: latex/dash.md
        - Make LaTeX formulas online images: latex/online_equation.md
    - WebFrontEnd:
        - HTML:
            - inline-block: webfrontend/html/inline_block.md
    - English:
        - english/one_that.md
        - english/just_remenber.md
        - english/adverb.md
        - english/conjunction.md
theme:
    name: material
    nav_style: dark
    favicon: images/logo/favicon.ico
    icon:
        logo: material/school
    language: en
    highlightjs: true
    # features:
    #     tabs

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        toc_depth: 3
    - sane_lists
    - codehilite:
        # linenums: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.magiclink
    - admonition
    - def_list

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "css/custom.css"
    
plugins:
    - search:
        separator: '[\s\-\.]+'
