name: sync-articles-from-zenn-to-qiita

on:
  push:
    branches:
      - main
    paths:
      - 'articles/*'
      - 'images/**/*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.10"
  NODE_VERSION: "18.15.0"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      - name: Checkout main branch in repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Setup Qiita CLI
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: |
          mkdir -p ~/.config/qiita-cli/
          echo '{"default":"qiita","credentials":[{"name":"qiita","accessToken":"'$QIITA_TOKEN'"}]}' >| ~/.config/qiita-cli/credentials.json

      - name: Sync article
        run: |
          files=($(git diff-tree --no-commit-id --name-only -r $(git rev-parse "HEAD^") $(git rev-parse "HEAD")))
          for file in ${files[@]}; do
            if [[ $file =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo $file | sed -e 's/articles\/\(.*\)\.md/\1/')
              poetry run task z2q $article_id
            fi
          done

      - name: Stamp synced article id to Zenn articles
        run: |
          articles=$(git diff --no-commit-id --name-only articles)
          for article in ${articles[@]}; do
            if [[ $article =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo $article | sed -e 's/articles\/\(.*\)\.md/\1/')
              git add ${article}
              git commit -m "[zenn] Stamp id of synced article on ${article_id}" --no-verify
              git push origin main
            fi
          done

      - name: Create pull requests of Qiita articles
        run: |
          articles=$(git diff --no-commit-id --name-only public)
          for article in ${articles[@]}; do
            if [[ $article =~ ^public/.*\.md$ ]]; then
              article_id=$(echo $article | sed -e 's/public\/\(.*\)\.md/\1/')
              branch_name="qiita-${article_id}"
              git switch -c ${branch_name}
              git add ${article}
              git commit -m "[qiita] Sync article of ${article_id} from Zenn" --no-verify
              git push origin ${branch_name}
              body=echo -e "Qiita: ${article}"
              gh pr create --base main --head ${branch_name} --title "Sync article of ${article_id} from Zenn to Qiita" --body ${body}
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
