name: sync-articles-from-zenn-to-qiita

on:
  push:
    branches:
      - main
    paths:
      - 'articles/*'
      - 'images/**/*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.10"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      - name: Checkout main branch in repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Sync article
        run: |
          files=($(git diff-tree --no-commit-id --name-only -r $(git rev-parse "HEAD^") $(git rev-parse "HEAD")))
          for file in ${files[@]}; do
            echo $file
            if [[ $file =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo $file | sed -e 's/articles\/\(.*\)\.md/\1/')
              poetry run task z2q $article_id
            fi
          done

      - name: Create pull requests
        run: |
          files=(git diff-tree --no-commit-id --name-only -r $(git rev-parse "HEAD^") $(git rev-parse "HEAD"))
          for file in ${files[@]}; do
            echo $file
            if [[ $file =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo $file | sed -e 's/articles\/\(.*\)\.md/\1/')
              qiita_article="./public/${article_id}.md"
              branch_name="qiita-sync-${article_id}-of-zenn"
              git switch -c ${branch_name}
              git add ${qiita_article}
              git commit -m "[qiita] Sync article of ${article_id} from Zenn"
              git push origin ${branch_name}
              gh pr create --base main --head ${branch_name} --title "Sync article of ${article_id} from Zenn to Qiita" --body "Zenn: ${file}\nQiita: ${qiita_article}"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
